export const data = [
  {
    id: 1,
    title: "Push Ups",
    duration: 1,
    currentSet: 1,
    totalSet: 2,
    image: require("./assets/Images/1.png"),
    isCompleted: false,
  },
  {
    id: 2,
    title: "Biceps Curl",
    duration: 1,
    currentSet: 1,
    totalSet: 2,
    image: require("./assets/Images/7.png"),
    isCompleted: false,
  },
  {
    id: 3,
    title: "Chest Press",
    duration: 2,
    currentSet: 1,
    totalSet: 2,
    image: require("./assets/Images/12.png"),
    isCompleted: false,
  },
  {
    id: 4,
    title: "Crunches",
    duration: 1,
    currentSet: 1,
    totalSet: 2,
    image: require("./assets/Images/2.png"),
    isCompleted: false,
  },
  {
    id: 5,
    title: "Sholder Press",
    duration: 2,
    currentSet: 1,
    totalSet: 2,
    image: require("./assets/Images/13.png"),
    isCompleted: false,
  },
];
